修改：     build_newifi-d2.yaml 	修改：     build_wrt1200ac.yaml

diff --git a/.github/workflows/build_wrt1200ac.yaml b/.github/workflows/build_wrt1200ac.yaml
--- a/.github/workflows/build_wrt1200ac.yaml
+++ b/.github/workflows/build_wrt1200ac.yaml
@@ -1,195 +1,265 @@
-#=================================================
-# https://github.com/P3TERX/Actions-OpenWrt
-# Description: Build OpenWrt using GitHub Actions
-# Lisence: MIT
-# Author: P3TERX
-# Blog: https://p3terx.com
-#=================================================
 #
-name: Build ARM WRT1200AC
+# This is free software, lisence use MIT.
+# 
+# Copyright (C) 2019 P3TERX <https://p3terx.com>
+# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
+# 
+# <https://github.com/KFERMercer/OpenWrt-CI>
+#
+####@
+name: Compile wrt1200 kernel TVH OpenWrt Images  
 
 on:
-  repository_dispatch:
-  release:
-    types: published
-  push:
-    branches:
-      - master
-    paths:
-      - '.config'
-#  schedule:
-#    - cron: 0 8 * * 5
-  watch:
-    types: started
+  #push:
+   # branches: 
+    #  - master
+  # schedule:
+  #   - cron: 0 20 * * *
+  #release:
+   # types: [published]
+  #watch:
+   # types: started
 
+  workflow_dispatch:    
+    
 env:
-  REPO_URL: https://github.com/x-wrt/x-wrt
-  REPO_URL1: https://github.com/coolsnowwolf/lede
-  REPO_BRANCH: master
+  #####change model here ####@# 
+  ROUTER_MODEL: wrt1200ac
+  TVH: true
+  BUILD_KERNEL_MODULES: true
+  DRIVERS_DIR: bin/targets/mvebu/drivers
+  KERNEL_CONFIG: 'myconfig/kernel_config.wrt1200ac'
+  #KERNEL_CONFIG_DIR: x-wrt/target/linux/ipq40xx
+  #KERNEL_CONFIG_DIR: target/linux/ramips/mt7620
+  #KERNEL_CONFIG_DIR: target/linux/ramips/mt7621
+  KERNEL_CONFIG_DIR: x-wrt/target/linux/mvebu
+  MAKEMENU_CONFIG: false
+  KERNEL_MENUCONFIG: false
+  CPU_MULTI_CORE: true
+  #5352319218:AAGkspTTlIjIRyfYlI7Egz4NciZ78bT3NF4
+  KERNEL_VERSION: '5.10'
+  UPDATE_MULTI_CORE_FILE1: myconfig/sys.lua
+  UPDATE_MULTI_CORE_FILE2: myconfig/processes.js
+  KERNEL_MODULE: myconfig/kernel_modules.txt
   FEEDS_CONF: feeds.conf.default
-  CONFIG_FILE: config.wrt1200ac
   DIY_P1_SH: diy-part1.sh
   DIY_P2_SH: diy-part2.sh
   SSH_ACTIONS: true
-  UPLOAD_BIN_DIR: true
   UPLOAD_FIRMWARE: true
-  UPLOAD_COWTRANSFER: false
   UPLOAD_WETRANSFER: false
   TZ: Asia/Shanghai
-
+  
 jobs:
-  build:
-    runs-on: ubuntu-18.04
+
+  build_openwrt:
+    ###@####
+    name: Build R619AC kernel 5.15 TVH firmware
+
+    runs-on: ubuntu-latest
+
     if: github.event.repository.owner.id == github.event.sender.id
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@master
 
-    - name: Initialization environment
-      env:
-        DEBIAN_FRONTEND: noninteractive
-      run: |
-        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
-        sudo -E apt-get -qq update
-        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
-        sudo -E apt-get -qq autoremove --purge
-        sudo -E apt-get -qq clean
-        sudo timedatectl set-timezone "$TZ"
-        sudo mkdir -p /workdir
-        sudo chown $USER:$GROUPS /workdir
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          ref: master
 
-    - name: Clone source code
-      working-directory: /workdir
-      run: |
-        df -hT $PWD
-        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
-        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
-        git clone --depth 1 $REPO_URL1 -b $REPO_BRANCH lede
-        ln -sf /workdir/lede $GITHUB_WORKSPACE/lede
-       # cd openwrt/package && git clone https://github.com/harrylwc/openwrt-dvb
-        
-    - name: Load custom feeds
-      run: |
-        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
-        chmod +x $DIY_P1_SH
-        cd openwrt
-        $GITHUB_WORKSPACE/$DIY_P1_SH
       
-    - name: Update feeds coolsnowwolf
-      run: cd lede && ./scripts/feeds update -a
-
-    - name: Install feeds coolsnowwolf
-      run: cd lede && ./scripts/feeds install -a
-
-    - name: Update feeds
-      run: cd openwrt && ./scripts/feeds update -a
-
-    - name: Install feeds
-      run: cd openwrt && ./scripts/feeds install -a -f
-
-    - name: Load custom configuration
-      run: |
-        [ -e files ] && mv files openwrt/files
-        [ -e dvb_driver.txt ] && cat dvb_driver.txt>> openwrt/target/linux/mvebu/config-5.10       
-        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
-        chmod +x $DIY_P2_SH
-        cd openwrt
-        $GITHUB_WORKSPACE/$DIY_P2_SH
-        
-  #  - name: SSH connection to Actions
-   #   uses: P3TERX/ssh2actions@main
-    #- name: Setup tmate session
-     # uses: mxschmitt/action-tmate@v3
-     # timeout-minutes: 250
-    #- name: SSH connection to Actions
-     # uses: harrylwc/debugger-action@master
-   # - name: SSH connection to Actions
-    #  uses: P3TERX/ssh2actions@main
-      
-    #- name: SSH connection to Actions
-     # uses: csexton/debugger-action/debugger-action@master
-     # if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')
-
-      #if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
-      env:
-        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
-        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-        
-    - name: Download package
-      id: package
-      run: |
-        cd openwrt
-        make defconfig
-        make download -j8
-        find dl -size -1024c -exec ls -l {} \;
-        find dl -size -1024c -exec rm -f {} \;
-
-    - name: Compile the firmware
-      id: compile
-      run: |
-        cd openwrt
-        echo -e "$(nproc) thread compile"
-        make -j$(nproc) V=s -i|| make -j1 || make -j1 V=s
-        #make V=s -i
-        echo "::set-output name=status::success"
-        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
-        [ -s DEVICE_NAME ] && echo "::addPath name=DEVICE_NAME::_$(cat DEVICE_NAME)"
-        echo "::addPath name=FILE_DATE::_$(date +"%Y%m%d%H%M")"
-    - name: Check space usage
-      if: (!cancelled()) 
-      run: df -hT
-
-    - name: Upload bin directory
-      uses: actions/upload-artifact@master
-      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
-      with:
-        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
-        path: openwrt/bin
-        
-    #- name: SSH connection to Actions
-    #  uses: P3TERX/ssh2actions@main        
-    #- name: SSH connection to Actions
-     # uses: harrylwc/debugger-action@master
-      #uses: csexton/debugger-action@master
+      - name: Update feeds & Load custom configuration
+        run: |
+          git clone https://github.com/x-wrt/x-wrt 
+          git clone https://github.com/coolsnowwolf/lede lede
+          ln -s $GITHUB_WORKSPACE/lede/package/lean $GITHUB_WORKSPACE/x-wrt/package/lean
+          lede/scripts/feeds update -a
+          rm -r x-wrt/package/lean/n2n_v2
+          cd x-wrt 
+          git clone https://github.com/jerrykuku/luci-theme-argon package/luci-theme-argon
+          chmod +x $GITHUB_WORKSPACE/$DIY_P2_SH
+          $GITHUB_WORKSPACE/$DIY_P2_SH
+          #sed -i 's/KERNEL_PATCHVER:=5.10/KERNEL_PATCHVER:=5.15/g' target/linux/ipq40xx/Makefile
+          ./scripts/feeds update -a
+          ./scripts/feeds install -a -f
+      - name: Space cleanup
+        env:
+          SSH_ACTIONS: true
+          DEBIAN_FRONTEND: noninteractive
+        run: |
+          docker rmi `docker images -q`
+          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
+          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
+          sudo -E apt-get update
+          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
+          sudo -E apt-get -y autoremove --purge
+          sudo -E apt-get clean
+          df -h
+     # - name: Run migrations
+      #  run: sh ./github/scripts/migrate.sh
+       # env:
+        # ENVIRONMENT_VARIABLE_NAME: ${{ secrets.ENVIRONMENT_VARIABLE_NAME }}
+          # echo 'HELLO_WORLD='${{ secrets.HELLO_WORLD }} >> .env // Code line 1
     
-    #- name: Setup tmate session
-     # uses: mxschmitt/action-tmate@v3
-      #timeout-minutes: 250
-    
-    #- name: SSH connection  for upload firmware
-     # uses: P3TERX/ssh2actions@main
+    #
+      #- name: Generate configuration file
+       #  run: |
+         
+          #rm -f ./.config*
+          #touch ./.config
+
+          #
+          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
+          # 例如:
+
+          #cat >> .config <<EOF
+          #CONFIG_TARGET_IMAGES_GZIP=y
+          #CONFIG_KERNEL_BUILD_USER="OpenWrt-CI"
+          #CONFIG_KERNEL_BUILD_DOMAIN="Azure"
+          #EOF
+
+          #
+          # ===============================================================
+          # 
+
+       #   sed -i 's/^[ \t]*//g' ./.config
+        #  make defconfig
+
+      - name: Make download
+        run: |
+          cd x-wrt 
+          make download -j8 || make download -j1 V=s
+          rm -rf $(find ./dl/ -size -1024c)
+          df -h
+      #- name: Setup upterm session
+        #if: env.MAKEMENU_CONFIG == 'true'
+        #uses: lhotari/action-upterm@v1
+            # - name: SSH connection for failure Debug
+            
+      - name: SSH connection for make menuconfig    
+        if: env.MAKEMENU_CONFIG == 'true'
+        uses: P3TERX/ssh2actions@main
+        env:
+         TELEGRAM_BOT_TOKEN: '5352319218:AAGkspTTlIjIRyfYlI7Egz4NciZ78bT3NF4'
+         TELEGRAM_CHAT_ID: 1373335316
+         
+      #- name: SSH connection for make menuconfig
+       # if: env.MAKEMENU_CONFIG == 'true'
+        #uses: P3TERX/ssh2actions@main
       
-    - name: Organize files
-      id: organize
-      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
-      run: |
-        cd openwrt  
-        mkdir bin/drivers && cp `find build_dir/target*/linux*/linux-*/ -name *.ko` bin/drivers/      
-        #cd bin/targets/*/*
-        #rm -rf packages
-        echo "::addPath name=FIRMWARE::$PWD"
-        echo "::set-output name=status::success"
-  
+      - name: Compile firmware
+        run: |
+          cd x-wrt 
+          make -j$(nproc) || make -j1 V=s
+          [ $? != 0 ] && make V=s || echo "build success"
+ 
+         
+          #     echo "======================="
+          #echo "Space usage:"
+          #echo "======================="
+          #df -h
+          #echo "======================="
+          #du -h ./ --max-depth=1
+          #du -h ~/work/x-wrt --max-depth=1 || true
 
       
-    - name: Upload firmware directory
-      uses: actions/upload-artifact@master
-      if: steps.organize.outputs.status == 'success' && !cancelled()
-      with:
-        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
-        path: ${{ env.FIRMWARE }}
+      -  name: SSH connection for failure Debug
+         if: ${{ failure() }}
+           #uses: lhotari/action-upterm@v1
+         uses: P3TERX/ssh2actions@main
+         env:
+          TELEGRAM_BOT_TOKEN: '5352319218:AAGkspTTlIjIRyfYlI7Egz4NciZ78bT3NF4'
+          TELEGRAM_CHAT_ID: '1373335316'
 
-    - name: Upload firmware to cowtransfer
-      if: steps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
-      run: |
-        curl -fsSL git.io/file-transfer | sh
-        ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
-        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
+      - name: SSH connection for KERNEL MENU CONFIG
+        if: env.KERNEL_MENUCONFIG == 'true'
+          # uses: lhotari/action-upterm@v1
+        uses: P3TERX/ssh2actions@main
 
-    - name: Upload firmware to WeTransfer
-      if: steps.organize.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
-      run: |
-        curl -fsSL git.io/file-transfer | sh
-        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
-        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
+ 
+      - name: Compile again after .config updated or add kernel modules
+        if: env.BUILD_KERNEL_MODULES == 'true'
+        run: |
+           cp myconfig/config.$ROUTER_MODEL.2 x-wrt/.config
+           #cat myconfig/config.tvh.ffmpeg >> .config
+           #[ -e $KERNEL_MODULE ] && cat $KERNEL_MODULE >> $KERNEL_CONFIG_DIR/config-$KERNEL_VERSION 
+           [ -e $KERNEL_CONFIG ] && cp -f $KERNEL_CONFIG $KERNEL_CONFIG_DIR/config-$KERNEL_VERSION
+           #[ -e $KERNEL_MODULE ] && cat $KERNEL_MODULE >> $KERNEL_CONFIG_DIR/config-$KERNEL_VERSION
+           cd x-wrt 
+           make -j$(nproc) || make -j1 
+           [ $? != 0 ] && make V=s || echo "build success" 
+      - name: SSH connection for failure Debug
+        if: ${{ failure() }}
+          # uses: lhotari/action-upterm@v1
+        uses: P3TERX/ssh2actions@main
+        env:
+          TELEGRAM_BOT_TOKEN: '5352319218:AAGkspTTlIjIRyfYlI7Egz4NciZ78bT3NF4'
+          TELEGRAM_CHAT_ID: '1373335316'
+      - name: Prepare artifact
+        run: |
+          # mkdir -p ./artifact/firmware
+          #mkdir -p ./artifact/package
+          #mkdir -p ./artifact/buildinfo
+          mkdir -p ./$DRIVERS_DIR
+          cp -f `find x-wrt/build_dir/target*/linux*/linux-*/ -name *.ko` $DRIVERS_DIR
+          cp -f `find x-wrt/build_dir/target*/linux*/rtl8821cu*/rtl8821cu.ko` openwrt/$DRIVERS_DIR        
+          #cp -f .config bin/
+          #cp -f myconfig/config.$ROUTER_MODEL.? bin/
+          #rm -rf $(find ./bin/targets/ -type d -name "packages")
+          #cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
+          #cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
+          #cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
+
+          grep '^CONFIG_TARGET.*DEVICE.*=y' x-wrt/.config|head -1 | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
+          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
+          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
+
+      - name: Upload bin directory
+        uses: actions/upload-artifact@master
+        with:
+          name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
+           #OpenWrt_bin_${{ env.ROUTER_MODEL }}
+          path: x-wrt/bin
+      - name: SSH connection for failure Debug
+        if: ${{ failure() }}
+        uses: P3TERX/ssh2actions@main
+        env:
+         TELEGRAM_BOT_TOKEN: '5352319218:AAGkspTTlIjIRyfYlI7Egz4NciZ78bT3NF4'
+         TELEGRAM_CHAT_ID: '1373335316'
+        ### also try to upload if fixed by ssh to server ####
+        
+      - name: Upload bin directory if failure
+        uses: actions/upload-artifact@master
+        if:  failure() 
+        with:
+          name: OpenWrt_bin_${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
+           #OpenWrt_bin_${{ env.ROUTER_MODEL }}_failure
+          path: x-wrt/bin
+
+
+            #- name: Deliver buildinfo
+            #uses: actions/upload-artifact@v2
+            #with:
+            #name: OpenWrt_buildinfo
+            #path: ./artifact/buildinfo/
+
+            
+            #- name: Deliver package
+            #uses: actions/upload-artifact@v2
+            #with:
+            #name: OpenWrt_package
+            #path: ./artifact/package/
+
+            #- name: Deliver firmware
+            #uses: actions/upload-artifact@v2
+        #with:
+        #name: OpenWrt_firmware
+        #path: ./bin/targets/
+
+      - name: Upload release asset
+        if: github.event == 'release'
+        uses: svenstaro/upload-release-action@v2
+        with:
+          repo_token: ${{ secrets.YOURTOKEN }}
+          file: ./artifact/firmware/*
+          tag: ${{ github.ref }}
+          file_glob: true
